# APPLICATION NAME
APP = matrixMul

# SOURCE FILES
APP_SRCS = main.c cluster.c kernels.c 

# NUMBER OF USED CLUSTER CORES
CORES ?= 1

# PERFORMANCE COUNTERS
APP_CFLAGS += -DPERF

# CHECK RESULT
APP_CFLAGS += -DDEBUG

# COMPILER FLAGS
APP_CFLAGS += -O3 -g3 -DNUM_CORES=${CORES}
APP_LDFLAGS +=

include $(RULES_DIR)/pmsis_rules.mk
